package com.onekin.customdiff.model.enums;

public enum SankeyLinkType {
	
	PACKAGEPRODUCT,
	ASSETPRODUCT,
	PRODUCTFEATURE,
	FEATUREASSET,
	FEATUREPACKAGE,
	PRODUCTPARENTFEATURE,
	PARENTFEATUREPACKAGE,
	PARENTFEATUREASSET,
	PACKAGEPRODUCTALL,
	ASSETALLPRODUCT,
	FEATURESIBLINGPACKAGE,
	FEATURESIBLINGCOREASSET,
	PRODUCTFEATURESIBLING;
}
